### ISSUE TITLE
Exposed mongodb+srv credentials

### ISSUE THREAD

**Issue by eth0izzle** [tnazevedo/rocketseat#2]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@aircnc-ztiqe.mongodb.net` in file [\oministack.9.0-aircns\backend\src\server.js](https://github.com/tnazevedo/rocketseat/blob/master\oministack.9.0-aircns\backend\src\server.js)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by talitaazevedo** [comment]
o projeto é open mesmo
